# Generated by Django 5.1.3 on 2024-12-05 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('bobot', models.FloatField()),
                ('tipe', models.CharField(max_length=100)),
                ('nilai_kepentingan', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NilaiKriteriaAnak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('anak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_kriteria', to='spk.anak')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_anak', to='spk.kriteria')),
            ],
        ),
    ]
