# Generated by Django 5.1.3 on 2024-12-05 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerbandinganKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_kepentingan', models.IntegerField(choices=[(1, 'Kedua elemen sama pentingnya'), (3, 'Elemen yang satu sedikit lebih penting daripada elemen yang lainnya'), (5, 'Elemen yang satu lebih penting daripada elemen yang lainnya'), (7, 'Satu elemen jelas lebih mutlak penting daripada elemen lainnya'), (9, 'Satu elemen mutlak penting daripada elemen lainnya')])),
                ('kriteria1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perbandingan1', to='spk.kriteria')),
                ('kriteria2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perbandingan2', to='spk.kriteria')),
            ],
        ),
    ]
