# Generated by Django 5.1.3 on 2024-12-05 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk', '0002_perbandingankriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='NilaiKepentingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('deskripsi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='bobot',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='nilai_kepentingan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spk.nilaikepentingan'),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='tipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spk.tipe'),
        ),
        migrations.DeleteModel(
            name='PerbandinganKriteria',
        ),
    ]
