# Generated by Django 5.1.3 on 2024-12-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk', '0003_nilaikepentingan_tipe_alter_kriteria_bobot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria',
            name='bobot',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
