# Generated by Django 5.1.3 on 2024-12-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk', '0005_kriteria_menggunakan_range_rangekategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='kriteria',
            name='nilai_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kriteria',
            name='nilai_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
